frontend:
	bash components/frontend.sh

mongodb:
	bash components/mongodb.sh

catalogue:
	bash components/catalogue.sh

cart:
	bash components/cart.sh

redis:
	bash components/redis.sh

user:
	bash components/user.sh

mysql:
	bash components/mysql.sh

rabbitmq:
	bash components/rabbitmq.sh

payment:
	bash components/payment.sh

shiping:
	bash components/shipping.sh